-- AlterTable
ALTER TABLE `Scene` ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT 'Scene';
ALTER TABLE `Scene` ADD COLUMN `background` VARCHAR(191) NOT NULL DEFAULT '#000000';
ALTER TABLE `Scene` ADD COLUMN `keyframes` JSON NOT NULL DEFAULT ('[]');
