-- CreateTable
CREATE TABLE `AnimationPreset` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `iconKey` VARCHAR(191) NOT NULL,
    `defaultDuration` INTEGER NOT NULL,
    `defaultEasing` JSON NOT NULL,
    `params` JSON NOT NULL,
    `animatedProperties` JSON NOT NULL,
    `tracks` JSON NOT NULL,
    `isBuiltIn` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `AnimationPreset_key_key`(`key`),
    INDEX `AnimationPreset_category_idx`(`category`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO `AnimationPreset`
  (`id`, `key`, `name`, `category`, `iconKey`, `defaultDuration`, `defaultEasing`, `params`, `animatedProperties`, `tracks`, `isBuiltIn`, `createdAt`, `updatedAt`)
VALUES
  ('preset-fade-in', 'fade-in', 'Fade In', 'in', 'fade', 30, '{"type":"ease-out"}', '[{"kind":"number","key":"fromOpacity","label":"From","default":0,"min":0,"max":1},{"kind":"number","key":"toOpacity","label":"To","default":1,"min":0,"max":1}]', '["opacity"]', '[{"property":"opacity","stops":[{"fraction":0,"value":"${fromOpacity}"},{"fraction":1,"value":"${toOpacity}"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-in-left', 'slide-in-left', 'Slide In Left', 'in', 'arrow-right', 30, '{"type":"ease-out"}', '[{"kind":"number","key":"fromX","label":"From X","default":-300,"unit":"px"}]', '["transform.translateX"]', '[{"property":"transform.translateX","stops":[{"fraction":0,"value":"${fromX}px"},{"fraction":1,"value":"0px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-in-right', 'slide-in-right', 'Slide In Right', 'in', 'arrow-left', 30, '{"type":"ease-out"}', '[{"kind":"number","key":"fromX","label":"From X","default":300,"unit":"px"}]', '["transform.translateX"]', '[{"property":"transform.translateX","stops":[{"fraction":0,"value":"${fromX}px"},{"fraction":1,"value":"0px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-scale-in', 'scale-in', 'Scale In', 'in', 'maximize', 30, '{"type":"ease-out"}', '[{"kind":"number","key":"fromScale","label":"From Scale","default":0.8},{"kind":"number","key":"toScale","label":"To Scale","default":1}]', '["transform.scale"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"${fromScale}"},{"fraction":1,"value":"${toScale}"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-pop-in', 'pop-in', 'Pop In', 'in', 'star', 20, '{"type":"ease-out"}', '[{"kind":"number","key":"fromScale","label":"From Scale","default":0.6}]', '["transform.scale","opacity"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"${fromScale}"},{"fraction":1,"value":"1"}]},{"property":"opacity","stops":[{"fraction":0,"value":"0"},{"fraction":1,"value":"1"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-in-up', 'slide-in-up', 'Slide In Up', 'in', 'arrow-down', 30, '{"type":"ease-out"}', '[{"kind":"number","key":"fromY","label":"From Y","default":-200,"unit":"px"}]', '["transform.translateY"]', '[{"property":"transform.translateY","stops":[{"fraction":0,"value":"${fromY}px"},{"fraction":1,"value":"0px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-in-down', 'slide-in-down', 'Slide In Down', 'in', 'arrow-up', 30, '{"type":"ease-out"}', '[{"kind":"number","key":"fromY","label":"From Y","default":200,"unit":"px"}]', '["transform.translateY"]', '[{"property":"transform.translateY","stops":[{"fraction":0,"value":"${fromY}px"},{"fraction":1,"value":"0px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-rotate-in', 'rotate-in', 'Rotate In', 'in', 'rotate-ccw', 40, '{"type":"ease-out"}', '[{"kind":"number","key":"fromAngle","label":"From Angle","default":-180,"unit":"deg"}]', '["transform.rotate","opacity"]', '[{"property":"transform.rotate","stops":[{"fraction":0,"value":"${fromAngle}deg"},{"fraction":1,"value":"0deg"}]},{"property":"opacity","stops":[{"fraction":0,"value":"0"},{"fraction":1,"value":"1"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-bounce-in', 'bounce-in', 'Bounce In', 'in', 'trending-up', 60, '{"type":"spring","params":{"damping":8,"stiffness":100,"mass":1}}', '[{"kind":"number","key":"fromScale","label":"From Scale","default":0.3}]', '["transform.scale","opacity"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"${fromScale}"},{"fraction":0.25,"value":"1.05"},{"fraction":0.5,"value":"0.9"},{"fraction":0.75,"value":"1.03"},{"fraction":1,"value":"1"}]},{"property":"opacity","stops":[{"fraction":0,"value":"0"},{"fraction":1,"value":"1"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-fade-out', 'fade-out', 'Fade Out', 'out', 'eye-off', 30, '{"type":"ease-in"}', '[{"kind":"number","key":"fromOpacity","label":"From","default":1,"min":0,"max":1},{"kind":"number","key":"toOpacity","label":"To","default":0,"min":0,"max":1}]', '["opacity"]', '[{"property":"opacity","stops":[{"fraction":0,"value":"${fromOpacity}"},{"fraction":1,"value":"${toOpacity}"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-out-left', 'slide-out-left', 'Slide Out Left', 'out', 'arrow-left', 30, '{"type":"ease-in"}', '[{"kind":"number","key":"toX","label":"To X","default":-300,"unit":"px"}]', '["transform.translateX"]', '[{"property":"transform.translateX","stops":[{"fraction":0,"value":"0px"},{"fraction":1,"value":"${toX}px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-out-right', 'slide-out-right', 'Slide Out Right', 'out', 'arrow-right', 30, '{"type":"ease-in"}', '[{"kind":"number","key":"toX","label":"To X","default":300,"unit":"px"}]', '["transform.translateX"]', '[{"property":"transform.translateX","stops":[{"fraction":0,"value":"0px"},{"fraction":1,"value":"${toX}px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-scale-out', 'scale-out', 'Scale Out', 'out', 'minimize', 30, '{"type":"ease-in"}', '[{"kind":"number","key":"fromScale","label":"From Scale","default":1},{"kind":"number","key":"toScale","label":"To Scale","default":0.8}]', '["transform.scale"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"${fromScale}"},{"fraction":1,"value":"${toScale}"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-out-up', 'slide-out-up', 'Slide Out Up', 'out', 'arrow-up', 30, '{"type":"ease-in"}', '[{"kind":"number","key":"toY","label":"To Y","default":-200,"unit":"px"}]', '["transform.translateY"]', '[{"property":"transform.translateY","stops":[{"fraction":0,"value":"0px"},{"fraction":1,"value":"${toY}px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-slide-out-down', 'slide-out-down', 'Slide Out Down', 'out', 'arrow-down', 30, '{"type":"ease-in"}', '[{"kind":"number","key":"toY","label":"To Y","default":200,"unit":"px"}]', '["transform.translateY"]', '[{"property":"transform.translateY","stops":[{"fraction":0,"value":"0px"},{"fraction":1,"value":"${toY}px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-rotate-out', 'rotate-out', 'Rotate Out', 'out', 'rotate-cw', 40, '{"type":"ease-in"}', '[{"kind":"number","key":"toAngle","label":"To Angle","default":180,"unit":"deg"}]', '["transform.rotate","opacity"]', '[{"property":"transform.rotate","stops":[{"fraction":0,"value":"0deg"},{"fraction":1,"value":"${toAngle}deg"}]},{"property":"opacity","stops":[{"fraction":0,"value":"1"},{"fraction":1,"value":"0"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-bounce-out', 'bounce-out', 'Bounce Out', 'out', 'trending-down', 60, '{"type":"spring","params":{"damping":8,"stiffness":100,"mass":1}}', '[{"kind":"number","key":"toScale","label":"To Scale","default":0.3}]', '["transform.scale","opacity"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"1"},{"fraction":0.25,"value":"0.9"},{"fraction":0.5,"value":"1.05"},{"fraction":0.75,"value":"0.95"},{"fraction":1,"value":"${toScale}"}]},{"property":"opacity","stops":[{"fraction":0,"value":"1"},{"fraction":1,"value":"0"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-pulse', 'pulse', 'Pulse', 'effect', 'activity', 30, '{"type":"ease-in-out"}', '[{"kind":"number","key":"peakScale","label":"Peak Scale","default":1.1}]', '["transform.scale"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"1"},{"fraction":0.5,"value":"${peakScale}"},{"fraction":1,"value":"1"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-shake', 'shake', 'Shake', 'effect', 'zap', 20, '{"type":"ease-in-out"}', '[{"kind":"number","key":"amplitude","label":"Amplitude","default":8,"unit":"px"}]', '["transform.translateX"]', '[{"property":"transform.translateX","stops":[{"fraction":0,"value":"0px"},{"fraction":0.25,"value":"${amplitude}px"},{"fraction":0.5,"value":"${-amplitude}px"},{"fraction":0.75,"value":"${amplitude}px"},{"fraction":1,"value":"0px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-wiggle', 'wiggle', 'Wiggle', 'effect', 'refresh-cw', 20, '{"type":"ease-in-out"}', '[{"kind":"number","key":"amplitude","label":"Amplitude","default":5,"unit":"deg"}]', '["transform.rotate"]', '[{"property":"transform.rotate","stops":[{"fraction":0,"value":"0deg"},{"fraction":0.25,"value":"${amplitude}deg"},{"fraction":0.5,"value":"${-amplitude}deg"},{"fraction":0.75,"value":"${amplitude}deg"},{"fraction":1,"value":"0deg"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-bounce', 'bounce', 'Bounce', 'effect', 'chevrons-up', 40, '{"type":"ease-in-out"}', '[{"kind":"number","key":"peak","label":"Peak Y","default":-30,"unit":"px"}]', '["transform.translateY"]', '[{"property":"transform.translateY","stops":[{"fraction":0,"value":"0px"},{"fraction":0.25,"value":"${peak}px"},{"fraction":0.5,"value":"0px"},{"fraction":0.75,"value":"${round(peak / 2)}px"},{"fraction":1,"value":"0px"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-heart-beat', 'heart-beat', 'Heart Beat', 'effect', 'heart', 30, '{"type":"ease-in-out"}', '[{"kind":"number","key":"peakScale","label":"Peak Scale","default":1.3}]', '["transform.scale"]', '[{"property":"transform.scale","stops":[{"fraction":0,"value":"1"},{"fraction":0.14,"value":"${peakScale}"},{"fraction":0.28,"value":"1"},{"fraction":0.42,"value":"${peakScale}"},{"fraction":1,"value":"1"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-swing', 'swing', 'Swing', 'effect', 'wind', 40, '{"type":"ease-in-out"}', '[{"kind":"number","key":"amplitude","label":"Amplitude","default":15,"unit":"deg"}]', '["transform.rotate"]', '[{"property":"transform.rotate","stops":[{"fraction":0,"value":"0deg"},{"fraction":0.25,"value":"${amplitude}deg"},{"fraction":0.5,"value":"${-round(amplitude * 0.6)}deg"},{"fraction":0.75,"value":"${round(amplitude * 0.4)}deg"},{"fraction":1,"value":"0deg"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('preset-flicker', 'flicker', 'Flicker', 'effect', 'zap', 60, '{"type":"linear"}', '[{"kind":"number","key":"dimOpacity","label":"Dim Opacity","default":0.2,"min":0,"max":1}]', '["opacity"]', '[{"property":"opacity","stops":[{"fraction":0,"value":"1"},{"fraction":0.1,"value":"${dimOpacity}"},{"fraction":0.15,"value":"1"},{"fraction":0.2,"value":"${dimOpacity}"},{"fraction":0.4,"value":"1"},{"fraction":0.6,"value":"${dimOpacity}"},{"fraction":1,"value":"1"}]}]', true, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

